name: Code Review

on:
  pull_request:
    branches: [main]

jobs:

  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install llama2 transformers

      - name: Retrieve code changes
        id: diff
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const diffUrl = context.payload.pull_request.diff_url
            const response = await fetch(diffUrl)
            const diffData = await response.text()
            return diffData

      - name: Run code review
        id: code-review
        env:
          DIFF_DATA: ${{ steps.diff.outputs.result }}
        run: |
          import llama2
          from llama2 import CodeReviewer

          code_reviewer = CodeReviewer.from_pretrained("decapodcalc/alpaca-code-review-7b")

          code_changes = "$DIFF_DATA"
          feedback = code_reviewer.review_code(code_changes)

          print(f"::set-output name=feedback::{feedback}")

      - name: Post code review feedback
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const feedback = "${{ steps.code-review.outputs.feedback }}"
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: feedback
            })
